import { NextResponse } from 'next/server'
import { createClient, createAdminClient } from '@/lib/supabase/server'

export const dynamic = 'force-dynamic'

async function guard() { const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return { error: NextResponse.json({ error: 'Non autenticato' }, { status: 401 }) }; const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single(); if (profile?.role !== 'super_admin') return { error: NextResponse.json({ error: 'Solo il Super Admin può gestire i provider' }, { status: 403 }) }; return { user } }

export async function GET() { const auth = await guard(); if (auth.error) return auth.error; const supabase = createClient(); const { data: providers, error } = await supabase.from('provider_credentials').select('id, provider, label, secret_reference, active, created_at, updated_at').order('provider'); if (error) return NextResponse.json({ error: error.message }, { status: 400 }); return NextResponse.json({ providers }) }
export async function POST(request: Request) { const auth = await guard(); if (auth.error) return auth.error; const { provider, label, secretReference, active = true } = await request.json(); if (!provider || !label || !secretReference || !/^[A-Z][A-Z0-9_]+$/.test(secretReference)) return NextResponse.json({ error: 'Indica provider, label e una variabile ambiente valida (es. TELNYX_API_KEY)' }, { status: 400 }); const admin = createAdminClient(); const { data: saved, error } = await admin.from('provider_credentials').upsert({ provider, label, secret_reference: secretReference, active, created_by: auth.user.id, updated_at: new Date().toISOString() }, { onConflict: 'provider,label' }).select('id, provider, label, secret_reference, active').single(); if (error) return NextResponse.json({ error: error.message }, { status: 400 }); await admin.from('audit_logs').insert({ actor_id: auth.user.id, action: 'provider_reference.saved', entity_type: 'provider_credential', entity_id: saved.id, metadata: { provider, label, secretReference } }); return NextResponse.json({ provider: saved }, { status: 201 }) }
