'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Check, FileText, MessageSquare, Mic, Save, Search, Send, ShieldCheck, Users } from 'lucide-react'

const MINUTES = [150, 300, 500, 1000, 2000, 4000, 7000, 10000]
const TIERS = [{ key: 'base', name: 'Base' }, { key: 'evoluto', name: 'Evoluto' }, { key: 'enterprise', name: 'Enterprise' }]
const DAYS = ['Lunedì', 'Martedì', 'Mercoledì', 'Giovedì', 'Venerdì', 'Sabato', 'Domenica']
type CatalogItem = { plan_type: string; included_minutes: number; billing_cycle: string; price_cents: number }
type NumberItem = { phone_number: string; phone_number_type?: string; region_information?: { region_name?: string } }
type Faq = { question: string; answer: string; active: boolean }
type Department = { name: string; description: string; routingTarget: string }

const nav = [
  { group: 'ORGANIZZAZIONE', items: [['business', 'Informazioni attività'], ['catalog', 'Catalogo']] },
  { group: 'CANALI', items: [['vapi', 'Agenti Vocali (Vapi)'], ['meta', 'Meta'], ['whatsapp', 'WhatsApp'], ['chatbot', 'Chatbot']] },
  { group: 'CRM', items: [['contacts', 'Contatti'], ['lists', 'Liste'], ['leads', 'Lead']] },
  { group: 'AMMINISTRAZIONE', items: [['users', 'Utenti e Ruoli'], ['plan', 'Gestione Piano'], ['company', 'Informazioni Azienda']] },
]

export default function NuovoCliente() {
  const [active, setActive] = useState('business'); const [tab, setTab] = useState('details')
  const [catalog, setCatalog] = useState<CatalogItem[]>([]); const [catalogError, setCatalogError] = useState<string | null>(null)
  const [minutesIndex, setMinutesIndex] = useState(2); const [billingCycle, setBillingCycle] = useState<'trimestrale' | 'annuale'>('annuale'); const [planType, setPlanType] = useState('evoluto')
  const [form, setForm] = useState({ companyName: '', vatNumber: '', contactEmail: '', contactPhone: '', billingAddress: '', websiteUrl: '', smsSenderName: '', description: '', city: '', postalCode: '', province: '' })
  const [socialLinks, setSocialLinks] = useState('{}'); const [regularHours, setRegularHours] = useState<Record<string, string>>(Object.fromEntries(DAYS.map((day) => [day, '09:00-18:00'])))
  const [faqs, setFaqs] = useState<Faq[]>([]); const [departments, setDepartments] = useState<Department[]>([]); const [ragFiles, setRagFiles] = useState<File[]>([]); const [companyDocument, setCompanyDocument] = useState<File | null>(null); const [representativeDocument, setRepresentativeDocument] = useState<File | null>(null)
  const [vapiConfig, setVapiConfig] = useState({ systemPrompt: '', localeInstructions: 'Rispondi in italiano.', voice: 'rachel', model: 'gpt-4o-mini' }); const [channelConfig, setChannelConfig] = useState('{}')
  const [search, setSearch] = useState({ city: '', prefix: '' }); const [numbers, setNumbers] = useState<NumberItem[]>([]); const [selectedNumber, setSelectedNumber] = useState('')
  const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); const [searching, setSearching] = useState(false); const [clientId, setClientId] = useState<string | null>(null)
  const includedMinutes = MINUTES[minutesIndex]

  useEffect(() => { let mounted = true; const load = async () => { try { const response = await fetch('/api/admin/plans', { cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw new Error(body.error); if (mounted) setCatalog(body.catalog || []) } catch (caught) { if (mounted) setCatalogError(caught instanceof Error ? caught.message : 'Listino non disponibile') } }; void load(); return () => { mounted = false } }, [])
  const prices = useMemo(() => Object.fromEntries(TIERS.map((tier) => { const item = catalog.find((entry) => entry.plan_type === tier.key && entry.included_minutes === includedMinutes && entry.billing_cycle === billingCycle); return [tier.key, item ? item.price_cents / 100 : 0] })), [catalog, includedMinutes, billingCycle])
  const update = (name: string, value: string) => setForm((current) => ({ ...current, [name]: value }))
  const parseJson = (value: string, fallback: object) => { try { return JSON.parse(value) } catch { return fallback } }

  async function searchNumbers(event: React.FormEvent) { event.preventDefault(); setSearching(true); setError(null); try { const params = new URLSearchParams({ 'filter[country_code]': 'IT', 'filter[phone_number_type]': 'local', 'filter[limit]': '20' }); if (search.city) params.set('filter[locality]', search.city); if (search.prefix) params.set('filter[phone_number][contains]', `+39${search.prefix}`); const response = await fetch(`/api/admin/provisioning/telnyx?${params}`); const body = await response.json(); if (!response.ok) throw new Error(body.error); setNumbers(body.data || []); setMessage(`${(body.data || []).length} numeri trovati.`) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Ricerca fallita') } finally { setSearching(false) } }

  async function saveOnboarding(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(null); setMessage(null); try {
    if (!form.companyName || !form.vatNumber || !form.contactEmail || !form.billingAddress) throw new Error('Completa ragione sociale, P.IVA, email e indirizzo legale.')
    const clientResponse = await fetch('/api/admin/clienti', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ companyName: form.companyName, vatNumber: form.vatNumber, contactEmail: form.contactEmail, contactPhone: form.contactPhone, billingAddress: form.billingAddress, planType, includedMinutes, billingCycle, monthlyPrice: prices[planType], sendInvite: true }) }); const clientBody = await clientResponse.json(); if (!clientResponse.ok) throw new Error(clientBody.error || 'Creazione cliente fallita'); const id = clientBody.client?.id; if (!id) throw new Error('clientId non restituito'); setClientId(id)
    const onboarding = new FormData(); onboarding.set('clientId', id); Object.entries(form).forEach(([key, value]) => onboarding.set(key, value)); onboarding.set('socialLinks', socialLinks); onboarding.set('regularHours', JSON.stringify(regularHours)); onboarding.set('specialHours', '[]'); onboarding.set('faqs', JSON.stringify(faqs)); onboarding.set('departments', JSON.stringify(departments)); onboarding.set('vapiConfig', JSON.stringify(vapiConfig)); onboarding.set(active === 'meta' ? 'metaConfig' : active === 'whatsapp' ? 'whatsappConfig' : active === 'chatbot' ? 'chatbotConfig' : 'metaConfig', channelConfig); ragFiles.slice(0, 2).forEach((file, index) => onboarding.set(`ragDocument${index + 1}`, file)); const saveResponse = await fetch('/api/admin/onboarding', { method: 'POST', body: onboarding }); const saveBody = await saveResponse.json(); if (!saveResponse.ok) throw new Error(saveBody.error || 'Salvataggio onboarding fallito')
    if (selectedNumber) { if (!companyDocument || !representativeDocument) throw new Error('Carica visura camerale e documento del legale rappresentante.'); const compliance = new FormData(); compliance.set('clientId', id); compliance.set('phoneNumberType', 'local'); compliance.set('customerReference', form.companyName); compliance.set('requirements', JSON.stringify({ company_name: form.companyName, vat_number: form.vatNumber, address: form.billingAddress, contact_phone: form.contactPhone })); compliance.set('companyDocument', companyDocument); compliance.set('representativeDocument', representativeDocument); const c = await fetch('/api/admin/provisioning/telnyx/compliance', { method: 'POST', body: compliance }); const cb = await c.json(); if (!c.ok) throw new Error(cb.error || 'Compliance Telnyx fallita'); const order = await fetch('/api/admin/provisioning/telnyx', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ clientId: id, phoneNumbers: [selectedNumber], requirementGroupId: cb.requirementGroup?.id }) }); const ob = await order.json(); if (!order.ok) throw new Error(ob.error || 'Ordine Telnyx fallito'); const vp = await fetch('/api/admin/provisioning/vapi', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ clientId: id, phoneNumber: selectedNumber, phoneNumberId: ob.phoneRecords?.[0]?.id, assistant: { name: `ProntoAI24 - ${form.companyName}`, firstMessage: `Benvenuto in ${form.companyName}. Come posso aiutarti?`, model: { provider: 'openai', model: vapiConfig.model, messages: [{ role: 'system', content: `${vapiConfig.systemPrompt}\n${vapiConfig.localeInstructions}` }] }, voice: { provider: '11labs', voiceId: vapiConfig.voice } } }) }); const vb = await vp.json(); if (!vp.ok) throw new Error(vb.error || 'Provisioning Vapi fallito') }
    setMessage('Onboarding salvato. Cliente, configurazione attività e moduli AI sono pronti.'); setActive('business'); setTab('details')
  } catch (caught) { setError(caught instanceof Error ? caught.message : 'Salvataggio fallito') } finally { setLoading(false) } }

  function addFaq() { setFaqs((items) => [...items, { question: '', answer: '', active: true }]) }
  function addDepartment() { setDepartments((items) => [...items, { name: '', description: '', routingTarget: '' }]) }
  const field = (name: keyof typeof form, label: string, required = false) => <label className="text-sm font-bold">{label}<input required={required} value={form[name]} onChange={(event) => update(name, event.target.value)} className="mt-2 w-full rounded-2xl border border-[var(--line)] bg-white px-4 py-3" /></label>

  return <main className="min-h-screen bg-[#f7fbff] px-4 py-6 text-[var(--ink)] lg:px-8"><div className="mx-auto max-w-7xl"><Link href="/admin/clienti" className="inline-flex items-center gap-2 text-sm font-bold text-[var(--blue)]"><ArrowLeft size={16} /> Clienti</Link><div className="mt-6 grid gap-6 lg:grid-cols-[260px_1fr]"><aside className="rounded-3xl bg-[var(--ink)] p-5 text-white"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#b7d5ff]">Onboarding tenant</p><h1 className="mt-3 text-2xl font-bold">Configura cliente</h1><div className="mt-7 space-y-6">{nav.map((section) => <div key={section.group}><p className="mb-2 text-[10px] font-bold tracking-[.16em] text-white/50">{section.group}</p><div className="grid gap-1">{section.items.map(([key, label]) => <button type="button" key={key} onClick={() => setActive(key)} className={`rounded-xl px-3 py-2 text-left text-sm font-semibold ${active === key ? 'bg-white text-[var(--ink)]' : 'text-white/75 hover:bg-white/10'}`}>{label}</button>)}</div></div>)}</div></aside><section className="min-w-0 rounded-3xl border border-[var(--line)] bg-white p-6 sm:p-9"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--blue)]">{active === 'business' ? 'Informazioni attività' : active}</p><h2 className="mt-2 text-3xl font-bold">{active === 'business' ? 'Dati e conoscenza del tenant' : nav.flatMap((section) => section.items).find(([key]) => key === active)?.[1]}</h2></div>{clientId && <span className="rounded-full bg-[#e5f8f6] px-3 py-2 text-xs font-bold text-[var(--blue)]">Cliente creato</span>}</div>{active === 'business' && <div className="mt-7 flex flex-wrap gap-2 border-b border-[var(--line)] pb-3">{[['details', 'Dettagli'], ['place', 'Luogo'], ['hours', 'Orari'], ['departments', 'Dipartimenti'], ['faq', 'FAQ'], ['rag', 'Documenti RAG']].map(([key, label]) => <button type="button" key={key} onClick={() => setTab(key)} className={`rounded-full px-4 py-2 text-sm font-bold ${tab === key ? 'bg-[var(--ink)] text-white' : 'bg-[#f7fbff] text-[var(--muted)]'}`}>{label}</button>)}</div>}

<form onSubmit={saveOnboarding} className="mt-7 grid gap-6">{active === 'business' && tab === 'details' && <div className="grid gap-5 sm:grid-cols-2">{field('companyName', 'Nome azienda', true)}{field('vatNumber', 'Partita IVA', true)}{field('contactEmail', 'Email referente', true)}{field('websiteUrl', 'Sito web')}{field('contactPhone', 'Numero telefono')}{field('smsSenderName', 'Nome mittente SMS')}{<label className="text-sm font-bold sm:col-span-2">Descrizione azienda<textarea value={form.description} onChange={(e) => update('description', e.target.value)} rows={4} className="mt-2 w-full rounded-2xl border border-[var(--line)] px-4 py-3" /></label>}<label className="text-sm font-bold sm:col-span-2">Link social media JSON<textarea value={socialLinks} onChange={(e) => setSocialLinks(e.target.value)} rows={2} className="mt-2 w-full rounded-2xl border border-[var(--line)] px-4 py-3 font-mono text-xs" /></label></div>}
{active === 'business' && tab === 'place' && <div className="grid gap-5 sm:grid-cols-2">{field('billingAddress', 'Indirizzo sede', true)}{field('city', 'Città')}{field('postalCode', 'CAP')}{field('province', 'Provincia')}<p className="text-sm text-[var(--muted)] sm:col-span-2">La copertura geografica e la compliance del numero vengono aggiornate dagli eventi Telnyx.</p></div>}
{active === 'business' && tab === 'hours' && <div className="grid gap-3">{DAYS.map((day) => <label key={day} className="grid grid-cols-[120px_1fr] items-center gap-3 text-sm font-bold">{day}<input value={regularHours[day]} onChange={(e) => setRegularHours({ ...regularHours, [day]: e.target.value })} className="rounded-xl border border-[var(--line)] px-4 py-2" /></label>)}<p className="text-sm text-[var(--muted)]">Per festività e aperture straordinarie usa la configurazione JSON nelle API del tenant.</p></div>}
{active === 'business' && tab === 'departments' && <div className="grid gap-4"><button type="button" onClick={addDepartment} className="justify-self-start rounded-full bg-[var(--ink)] px-4 py-2 text-sm font-bold text-white">+ Nuovo reparto</button>{departments.map((department, index) => <div key={index} className="grid gap-3 rounded-2xl border border-[var(--line)] p-4 sm:grid-cols-3"><input placeholder="Nome reparto" value={department.name} onChange={(e) => setDepartments((items) => items.map((item, i) => i === index ? { ...item, name: e.target.value } : item))} className="rounded-xl border border-[var(--line)] px-3 py-2" /><input placeholder="Descrizione" value={department.description} onChange={(e) => setDepartments((items) => items.map((item, i) => i === index ? { ...item, description: e.target.value } : item))} className="rounded-xl border border-[var(--line)] px-3 py-2" /><input placeholder="Routing" value={department.routingTarget} onChange={(e) => setDepartments((items) => items.map((item, i) => i === index ? { ...item, routingTarget: e.target.value } : item))} className="rounded-xl border border-[var(--line)] px-3 py-2" /></div>)}</div>}
{active === 'business' && tab === 'faq' && <div className="grid gap-4"><button type="button" onClick={addFaq} className="justify-self-start rounded-full bg-[var(--ink)] px-4 py-2 text-sm font-bold text-white">+ Nuova FAQ</button>{faqs.map((faq, index) => <div key={index} className="grid gap-3 rounded-2xl border border-[var(--line)] p-4"><input placeholder="Domanda" value={faq.question} onChange={(e) => setFaqs((items) => items.map((item, i) => i === index ? { ...item, question: e.target.value } : item))} className="rounded-xl border border-[var(--line)] px-3 py-2" /><textarea placeholder="Risposta" value={faq.answer} onChange={(e) => setFaqs((items) => items.map((item, i) => i === index ? { ...item, answer: e.target.value } : item))} className="rounded-xl border border-[var(--line)] px-3 py-2" rows={3} /></div>)}</div>}
{active === 'business' && tab === 'rag' && <div className="grid gap-4"><div className="rounded-2xl bg-[#f7fbff] p-5"><p className="font-bold">Knowledge Base & Documenti RAG</p><p className="mt-1 text-sm text-[var(--muted)]">PDF, DOCX e TXT. I file vengono isolati per tenant in Supabase Storage.</p><input type="file" multiple accept=".pdf,.docx,.txt,application/pdf,text/plain" onChange={(e) => setRagFiles(Array.from(e.target.files || []))} className="mt-4 block text-sm" /></div>{ragFiles.map((file) => <p key={file.name} className="flex items-center gap-2 text-sm font-semibold"><FileText size={16} /> {file.name}</p>)}</div>}
{active === 'vapi' && <div className="grid gap-5"><div className="flex items-center gap-3"><Mic className="text-[var(--blue)]" /><p className="font-bold">Agente vocale Vapi</p></div><label className="text-sm font-bold">System Prompt<textarea value={vapiConfig.systemPrompt} onChange={(e) => setVapiConfig({ ...vapiConfig, systemPrompt: e.target.value })} rows={6} className="mt-2 w-full rounded-2xl border border-[var(--line)] px-4 py-3" /></label><label className="text-sm font-bold">Istruzioni locale<textarea value={vapiConfig.localeInstructions} onChange={(e) => setVapiConfig({ ...vapiConfig, localeInstructions: e.target.value })} rows={3} className="mt-2 w-full rounded-2xl border border-[var(--line)] px-4 py-3" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Voce ElevenLabs<input value={vapiConfig.voice} onChange={(e) => setVapiConfig({ ...vapiConfig, voice: e.target.value })} className="mt-2 w-full rounded-xl border border-[var(--line)] px-3 py-2" /></label><label className="text-sm font-bold">Modello<input value={vapiConfig.model} onChange={(e) => setVapiConfig({ ...vapiConfig, model: e.target.value })} className="mt-2 w-full rounded-xl border border-[var(--line)] px-3 py-2" /></label></div></div>}
{['meta', 'whatsapp', 'chatbot', 'contacts', 'lists', 'leads', 'users'].includes(active) && <div className="rounded-2xl bg-[#f7fbff] p-6"><div className="flex items-center gap-3"><MessageSquare className="text-[var(--blue)]" /><p className="font-bold">Configurazione modulo {active}</p></div><p className="mt-2 text-sm text-[var(--muted)]">Inserisci la configurazione JSON del modulo. Il salvataggio viene isolato nel tenant.</p><textarea value={channelConfig} onChange={(e) => setChannelConfig(e.target.value)} rows={8} className="mt-4 w-full rounded-2xl border border-[var(--line)] px-4 py-3 font-mono text-xs" /></div>}
{active === 'company' && <div className="grid gap-5 sm:grid-cols-2">{field('vatNumber', 'Partita IVA', true)}{field('billingAddress', 'Indirizzo legale', true)}<label className="text-sm font-bold">Visura camerale<input required type="file" accept="application/pdf,image/*" onChange={(e) => setCompanyDocument(e.target.files?.[0] || null)} className="mt-2 block w-full text-sm" /></label><label className="text-sm font-bold">ID legale rappresentante<input required type="file" accept="application/pdf,image/*" onChange={(e) => setRepresentativeDocument(e.target.files?.[0] || null)} className="mt-2 block w-full text-sm" /></label><div className="rounded-2xl bg-[#f7fbff] p-5 sm:col-span-2"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">Numero Telnyx +39</p><p className="text-sm text-[var(--muted)]">Cerca per città o prefisso senza acquistare il numero.</p></div><button type="button" onClick={(event) => void searchNumbers(event as unknown as React.FormEvent)} disabled={searching} className="inline-flex items-center gap-2 rounded-full bg-[var(--ink)] px-4 py-2 text-sm font-bold text-white"><Search size={15} />{searching ? 'Ricerca…' : 'Cerca'}</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><input placeholder="Città" value={search.city} onChange={(e) => setSearch({ ...search, city: e.target.value })} className="rounded-xl border border-[var(--line)] px-3 py-2" /><input placeholder="Prefisso" value={search.prefix} onChange={(e) => setSearch({ ...search, prefix: e.target.value })} className="rounded-xl border border-[var(--line)] px-3 py-2" /></div>{numbers.length > 0 && <div className="mt-4 grid gap-2 sm:grid-cols-2">{numbers.map((item) => <button type="button" key={item.phone_number} onClick={() => setSelectedNumber(item.phone_number)} className={`rounded-xl border-2 p-3 text-left font-bold ${selectedNumber === item.phone_number ? 'border-[var(--blue)] bg-white' : 'border-[var(--line)]'}`}>{item.phone_number}<span className="ml-2 text-xs font-normal text-[var(--muted)]">{item.region_information?.region_name || item.phone_number_type || 'Italia'}</span></button>)}</div>}{selectedNumber && <p className="mt-3 text-sm font-bold text-[var(--blue)]">Selezionato: {selectedNumber}</p>}</div><p className="text-sm text-[var(--muted)] sm:col-span-2">L’ordine e la verifica AGCOM vengono completati in modo asincrono dai webhook Telnyx.</p></div>}
{active === 'catalog' && <div className="rounded-2xl bg-[#f7fbff] p-6"><p className="font-bold">Catalogo prodotti e listini AI</p><p className="mt-2 text-sm text-[var(--muted)]">Il listino dinamico viene caricato dal pannello SuperAdmin e usato per il piano del tenant.</p></div>}
{active === 'plan' && <div className="grid gap-4"><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setBillingCycle('trimestrale')} className={`rounded-full px-4 py-2 text-sm font-bold ${billingCycle === 'trimestrale' ? 'bg-[var(--ink)] text-white' : 'bg-[#f7fbff]'}`}>Trimestrale</button><button type="button" onClick={() => setBillingCycle('annuale')} className={`rounded-full px-4 py-2 text-sm font-bold ${billingCycle === 'annuale' ? 'bg-[var(--ink)] text-white' : 'bg-[#f7fbff]'}`}>Annuale</button></div><input type="range" min="0" max={MINUTES.length - 1} value={minutesIndex} onChange={(e) => setMinutesIndex(Number(e.target.value))} /><div className="grid gap-3 md:grid-cols-3">{TIERS.map((tier) => <button type="button" key={tier.key} onClick={() => setPlanType(tier.key)} className={`rounded-2xl border-2 p-4 text-left ${planType === tier.key ? 'border-[var(--blue)]' : 'border-[var(--line)]'}`}><b>{tier.name}</b><p className="mt-2 text-2xl font-bold">{prices[tier.key] ? `€${prices[tier.key].toFixed(2)}` : '—'}</p><small>{includedMinutes} min/mese</small></button>)}</div></div>}
{active === 'company' || active === 'business' || active === 'vapi' || active === 'plan' ? <button disabled={loading || !prices[planType]} className="inline-flex items-center justify-center gap-2 rounded-full bg-[var(--ink)] px-6 py-4 font-bold text-white disabled:opacity-50"><Save size={16} />{loading ? 'Salvataggio…' : 'Salva e avvia onboarding'}</button> : <button type="submit" className="inline-flex items-center justify-center gap-2 rounded-full bg-[var(--ink)] px-6 py-4 font-bold text-white"><Save size={16} />Salva configurazione</button>}
{message && <p className="rounded-xl bg-[#e5f8f6] px-4 py-3 text-sm font-semibold">{message}</p>}{error && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-800">{error}</p>}</form></section></div></div></main>
}
