import Link from 'next/link'
import { ArrowLeft, ArrowUpRight, Building2, Mail } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'

export const dynamic = 'force-dynamic'

export default async function ClientiAdmin() {
  const supabase = createClient()
  const { data: clienti } = await supabase.from('clients').select('id, company_name, contact_email, contact_phone, status, vat_number, subscriptions(tier, minutes_package, status)').order('created_at', { ascending: false })
  return <main className="min-h-screen bg-[#f7fbff] px-6 py-10 text-[var(--ink)] lg:px-10"><div className="mx-auto max-w-7xl"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-bold text-[var(--blue)]"><ArrowLeft size={16} /> Dashboard Admin</Link><div className="mt-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[var(--blue)]">Anagrafiche</p><h1 className="mt-2 text-4xl font-bold">Clienti</h1><p className="mt-3 text-[var(--muted)]">Gestisci account, piani e stato operativo.</p></div><Link href="/admin/clienti/nuovo" className="rounded-full bg-[var(--ink)] px-5 py-3 text-sm font-bold text-white">+ Nuovo cliente</Link></div><div className="mt-10 overflow-hidden rounded-3xl border border-[var(--line)] bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#f7fbff] text-xs uppercase tracking-wider text-[var(--muted)]"><tr><th className="px-6 py-4">Cliente</th><th className="px-6 py-4">Contatto</th><th className="px-6 py-4">Piano</th><th className="px-6 py-4">Stato</th><th className="px-6 py-4" /></tr></thead><tbody>{(clienti ?? []).map((client: any) => <tr key={client.id} className="border-t border-[var(--line)]"><td className="px-6 py-5"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#eaf0ff]"><Building2 size={18} /></span><div><p className="font-bold">{client.company_name || 'Azienda non indicata'}</p><p className="mt-1 text-xs text-[var(--muted)]">{client.vat_number || 'P.IVA da completare'}</p></div></div></td><td className="px-6 py-5"><p>{client.contact_email}</p><p className="mt-1 text-xs text-[var(--muted)]">{client.contact_phone || 'Telefono non indicato'}</p></td><td className="px-6 py-5">{client.subscriptions?.[0] ? <><span className="font-bold">{client.subscriptions[0].tier}</span><span className="mt-1 block text-xs text-[var(--muted)]">{client.subscriptions[0].minutes_package} minuti</span></> : <span className="text-[var(--muted)]">Da assegnare</span>}</td><td className="px-6 py-5"><span className="rounded-full bg-[#f2f8d8] px-3 py-1 text-xs font-bold">{client.status}</span></td><td className="px-6 py-5 text-right"><ArrowUpRight size={18} className="ml-auto text-[var(--muted)]" /></td></tr>)}</tbody></table></div>{(!clienti || clienti.length === 0) && <div className="p-12 text-center text-sm text-[var(--muted)]">Non ci sono ancora clienti visibili.</div>}</div></div></main>
}
